#!/bin/bash
#
# Small script to view images from a  remote dir.
# 20090830:jpa:orig
#

pic_delay=${1:-3600}
reload_delay=${1:-300}
download_dir=/home/olpc/FramePics
pic_dir='~jpa/pics'
pics_url=http://abyo/~jpa/pics

view_cmd="feh --recursive --hide-pointer --full-screen --auto-zoom"

function GetConfig() {
  local cfg=${1:-$download_dir}/slideshow.config
  if [ -e $cfg ]; then
    eval $(egrep '^(reload_delay|pic_delay)=[0-9]+$' $cfg)
  fi
}


# Disable power management's energystar features.
xset -dpms

GetConfig
$view_cmd -D$pic_delay $download_dir&
fehpid=$!
trap "echo killing fehpid=$fehpid ; kill $fehpid" EXIT

while true; do
  date
  restart_feh=0

  rm -rf $download_dir.new
  mkdir -p $download_dir.new
  cd $download_dir.new

  wget -q --tries=1 --timeout=5 --directory-prefix=. \
    --no-host-directories \
    http://User:@192.168.1.10/IMAGE.JPG \
    $pics_url/slideshow.config
  wget -q --tries=1 --timeout=10 --no-parent --recursive \
    --accept=jpg,JPG,jpeg,JPG --directory-prefix=. \
    --no-host-directories \
    $pics_url 
  wget_res=$?
  pic_count=$(find . -type f ! -name slideshow.config | wc -l)
  echo "wget: res=$? files=$pic_count"
  cd ..

  diff --exclude=IMAGE.JPG --exclude=slideshow.config -r $download_dir.new $download_dir 
  diff_res=$?
  if [ $wget_res -eq 0 -a $pic_count -ge 2 -a $diff_res -ne 0 ]; then 
    mv $download_dir $download_dir.todelete
    mv $download_dir.new $download_dir
    restart_feh=1
  else
    mv $download_dir.new $download_dir.todelete
  fi
  rm -rf $download_dir.todelete

  if [ $restart_feh -ne 0 ]; then 
    kill $fehpid
    GetConfig 
    $view_cmd -D$pic_delay $download_dir&
    fehpid=$!
    trap "echo killing fehpid=$fehpid ; kill $fehpid" EXIT
    restart_feh=0
  fi
  # Delay could be pic_count based.
  sleep $((reload_delay + 10 * pic_delay / 100 ))
done

